// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.hgldp.grpc1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string no = 1;</code>
   */
  java.lang.String getNo();
  /**
   * <code>optional string no = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoBytes();
}
