// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.hgldp.grpc1;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>optional string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
