// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.hgldp.grpc;

public final class SimPleProto {
  private SimPleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\"\032\n\014HelloRequest\022\n\n\002no\030\001 \001(\t" +
      "\"\035\n\rHelloResponse\022\014\n\004name\030\001 \001(\t\":\n\017Stude" +
      "ntResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n" +
      "\004city\030\003 \001(\t\"@\n\023StudentResponseList\022)\n\017st" +
      "udentResponse\030\001 \003(\0132\020.StudentResponse\"%\n" +
      "\rStreamRequest\022\024\n\014request_info\030\001 \001(\t\"\'\n\016" +
      "StreamResponse\022\025\n\rresponse_info\030\001 \001(\t2\346\001" +
      "\n\013ExampleGrpc\0224\n\021sendSimpleMessage\022\r.Hel" +
      "loRequest\032\016.HelloResponse\"\000\0225\n\016getListMe" +
      "ssage\022\r.HelloRequest\032\020.StudentResponse\"\000",
      "0\001\0229\n\016getStudentList\022\r.HelloRequest\032\024.St" +
      "udentResponseList\"\000(\001\022/\n\006BiTalk\022\016.Stream" +
      "Request\032\017.StreamResponse\"\000(\0010\001B\037\n\016com.hg" +
      "ldp.grpcB\013SimPleProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "No", });
    internal_static_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloResponse_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
