// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.hgldp.grpc;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>optional string city = 3;</code>
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 3;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
