// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.hgldp.grpc;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.hgldp.grpc.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .StudentResponse studentResponse = 1;</code>
   */
  com.hgldp.grpc.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.hgldp.grpc.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .StudentResponse studentResponse = 1;</code>
   */
  com.hgldp.grpc.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
